import Head from 'next/head'
import Footer from '../CompSections/Footer'
import Navbar from '../comps/Navbar'
import ContactForm from '../comps/ContactForm'
import TrandingSection from '../comps/TrandingSection'
import AboutUsSection from '../CompSections/AboutUs'
import HomeSection from '../CompSections/HomeSection'
import PopTranding from '../CompSections/PopTranding'
import HowItWorks from '../CompSections/HowItWorks'
import FeedBackSection from '../CompSections/FeedBackSection'
import Sponsors from '../comps/Sponsors'
 
export default function Home() {
  return (
    <div >
      <Head>
        <title>WEB DEV Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
     <Navbar></Navbar>
       {/* Home Section */ }
       <HomeSection></HomeSection>
        
        {/* Sponsors */}
        <Sponsors></Sponsors>
       {/* about us */ }
       <AboutUsSection></AboutUsSection>
   
       {/* Popular tranding */}
      <PopTranding></PopTranding>

      {/* HOW it Works */}
      <HowItWorks></HowItWorks>
   
     {/* Tranding section */ }
     <div className="py-20">
       <p className="font-bold text-3xl text-center mb-5">Recent Added <strong className="text-blue-500">Tranding</strong>  Properties</p>
       <p className="text-thin text-gray-400 mb-5 text-center md:w-1/2 p-2 mx-auto">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
            incididunt ut labore e sed do eiusmod tempor incididunt ut labore e</p>
            <TrandingSection></TrandingSection>
     </div>
     {/* Clinets Feedback */}
     <FeedBackSection></FeedBackSection>
     {/* Contact Form */}
     <div className="py-20 lg:px-28 md:px-16 px-6">
       <ContactForm></ContactForm>
     </div>

     {/* Footer */ }
     <Footer></Footer>
    </div>
  )
}
